version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USE_GPU=${USE_GPU:-false}
        - TARGETPLATFORM=${PLATFORM:-linux/arm64/v8}
    platform: ${PLATFORM:-linux/arm64/v8}  # Default to ARM64 for M4
    environment:
      - PYTHONPATH=/app
      - USE_GPU=${USE_GPU:-false}
      - PYTORCH_CPU_THREADS=${CPU_THREADS:-4}
    volumes:
      - .:/app
      - ./memory/chroma_db:/app/memory/chroma_db
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${GPU_DRIVER:-none}
              count: ${GPU_COUNT:-0}
              capabilities: ["${GPU_CAPABILITIES:-}"]

  # Development service with hot reload
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Use the builder stage for development
      args:
        - USE_GPU=${USE_GPU:-false}
        - TARGETPLATFORM=${PLATFORM:-linux/arm64/v8}
    platform: ${PLATFORM:-linux/arm64/v8}
    environment:
      - PYTHONPATH=/app
      - USE_GPU=${USE_GPU:-false}
      - PYTHONUNBUFFERED=1
      - PYTORCH_CPU_THREADS=${CPU_THREADS:-4}
    volumes:
      - .:/app
      - ./memory/chroma_db:/app/memory/chroma_db
    ports:
      - "8000:8000"
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${GPU_DRIVER:-none}
              count: ${GPU_COUNT:-0}
              capabilities: ["${GPU_CAPABILITIES:-}"]

  # CPU-only service
  cpu:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USE_GPU=false
        - TARGETPLATFORM=${PLATFORM:-linux/arm64/v8}
    platform: ${PLATFORM:-linux/arm64/v8}
    environment:
      - PYTHONPATH=/app
      - USE_GPU=false
      - PYTORCH_CPU_THREADS=${CPU_THREADS:-4}
    volumes:
      - .:/app
      - ./memory/chroma_db:/app/memory/chroma_db
    ports:
      - "8000:8000" 